import React, { useState } from 'react';
import './RazorpayCheckout.css';

const RazorpayCheckout = ({ 
  amount, 
  orderDetails, 
  onSuccess, 
  onFailure, 
  onClose 
}) => {
  const [isLoading, setIsLoading] = useState(false);

  // Razorpay configuration
  const RAZORPAY_KEY = process.env.REACT_APP_RAZORPAY_KEY || 'rzp_test_your_key_here';

  const handleRazorpayPayment = () => {
    setIsLoading(true);

    // Create Razorpay order options
    const options = {
      key: RAZORPAY_KEY,
      amount: amount * 100, // Razorpay expects amount in paise
      currency: 'INR',
      name: 'KisanMitra',
      description: 'Fresh produce from local farmers',
      image: '/logo192.png',
      order_id: '', // Will be generated by backend
      handler: function (response) {
        // Payment successful
        console.log('Payment successful:', response);
        setIsLoading(false);
        if (onSuccess) {
          onSuccess({
            paymentId: response.razorpay_payment_id,
            orderId: response.razorpay_order_id,
            signature: response.razorpay_signature
          });
        }
      },
      prefill: {
        name: orderDetails.customerName || '',
        email: orderDetails.customerEmail || '',
        contact: orderDetails.customerPhone || ''
      },
      notes: {
        order_type: 'marketplace_purchase',
        items: orderDetails.items?.length || 0
      },
      theme: {
        color: '#4CAF50'
      },
      modal: {
        ondismiss: function() {
          setIsLoading(false);
          if (onClose) onClose();
        }
      }
    };

    // Check if Razorpay is loaded
    if (typeof window.Razorpay !== 'undefined') {
      const rzp = new window.Razorpay(options);
      
      rzp.on('payment.failed', function (response) {
        setIsLoading(false);
        console.error('Payment failed:', response.error);
        if (onFailure) {
          onFailure(response.error);
        }
      });

      rzp.open();
    } else {
      // Load Razorpay script dynamically
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.async = true;
      script.onload = () => {
        const rzp = new window.Razorpay(options);
        rzp.on('payment.failed', function (response) {
          setIsLoading(false);
          if (onFailure) onFailure(response.error);
        });
        rzp.open();
      };
      script.onerror = () => {
        setIsLoading(false);
        alert('Failed to load payment gateway. Please try again.');
      };
      document.body.appendChild(script);
    }
  };

  return (
    <div className="razorpay-checkout-overlay">
      <div className="razorpay-checkout-modal">
        <div className="modal-header">
          <h2>💳 Secure Payment</h2>
          <button onClick={onClose} className="close-btn">×</button>
        </div>
        
        <div className="modal-content">
          <div className="payment-summary">
            <div className="amount-display">
              <h3>Total Amount</h3>
              <div className="amount">₹{amount.toLocaleString('en-IN')}</div>
            </div>
            
            <div className="payment-features">
              <div className="feature">
                🔒 Bank-level security
              </div>
              <div className="feature">
                💳 All cards accepted
              </div>
              <div className="feature">
                📱 UPI & Wallets supported
              </div>
            </div>
          </div>
          
          <div className="payment-actions">
            <button 
              onClick={handleRazorpayPayment}
              disabled={isLoading}
              className="pay-now-btn"
            >
              {isLoading ? (
                <>
                  <span className="loading-spinner"></span>
                  Processing...
                </>
              ) : (
                <>
                  💳 Pay Now
                </>
              )}
            </button>
            
            <p className="payment-note">
              You will be redirected to Razorpay's secure payment gateway
            </p>
          </div>
          
          <div className="powered-by">
            <p>Powered by <strong>Razorpay</strong></p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RazorpayCheckout;